### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ktamiola** [jerrytheo/psopy#2]
Error:
```
[sudo] password for kamil: 
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    re.M | re.S).sub('', read('README.rst'))
  File "setup.py", line 25, in read
    encoding=kwargs.get('encoding', 'utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function
```
Step to reproduce:
`Python 2.7.15+`
`pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)`

**Comment by jerrytheo** [comment]
Hi. I am sorry, we do not support Python 2 as of now. Please let me know if you see this error on Python 3.
